
server:
  port: 8889

spring:
  cloud:
    gateway:
      routes:
        - id: UppercaseServiceV1
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/upper/**

        - id: LowercaseServiceV1
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/lower/**

        - id: UppercaseServiceHeaderV1
          uri: http://localhost:8082
          predicates:
            - Header=X-Transform-Id, ^upp$
            - Path=/api/v1/transform
          filters:
            - RewritePath=/api/v1/(?<segment>.*),/api/v1/upper

        - id: LowercaseServiceHeaderV1
          uri: http://localhost:8083
          predicates:
            - Header=X-Transform-Id, ^low$
            - Path=/api/v1/transform
          filters:
            - RewritePath=/api/v1/(?<segment>.*),/api/v1/lower
