server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Workspace/springboot-learning/support/config-repo/{application}